---
title: "class15"
author: "Nuo Tian"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Read sample genotypes data from ENSEMBLE

We downloaded genotypes data from ENSEMBLE on the MXL Mexican Ancestry in LA, CA dataset

What proportion of this data are G/G etc?

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```
```{r}
table(mxl$Genotype..forward.strand. )
```

## RNA-Seq result analysis for different genotypes of this SNP

```{r}
expr <- read.table("rs8067378_ENSG00000172057.6.txt")
head(expr)
```

```{r}
x <-  expr[ expr$geno == "G/G", ]
x
##summary(expr[ expr$geno == "G/G", ]$exp )
```

```{r}
summary(expr[ expr$geno == "A/G", ]$exp )
```

```{r}
summary(expr[ expr$geno == "A/A", ]$exp )
```

## Try a boxplot

We will use the `boxplot()` function and the input data will be **expr**. How do we draw a useful plot?

```{r}
boxplot(exp ~ geno, data = expr, notch=TRUE)
```


```{r}
hist(expr[ expr$geno == "G/G", ]$exp, breaks = 20 )
```


```{r}
nrow(expr)
```








